### ISSUE TITLE
App is crush when its installed

### ISSUE THREAD

**Issue by sharif-rcis** [rubygarage/shopapp-android#200]
java.lang.RuntimeException: Unable to create application com.shopapp.ShopApplication: java.lang.IllegalStateException: com.shopapp.di.module.RepositoryModule must be set
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5008)
        at android.app.ActivityThread.access$1600(ActivityThread.java:177)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1495)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5930)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
     Caused by: java.lang.IllegalStateException: com.shopapp.di.module.RepositoryModule must be set
        at com.shopapp.di.component.DaggerAppComponent$Builder.build(DaggerAppComponent.java:437)
        at com.shopapp.ShopApplication.buildAppComponent(ShopApplication.kt:51)
        at com.shopapp.ShopApplication.onCreate(ShopApplication.kt:35)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1019)

**Comment by vignesh-subash** [comment]
please help to resolve this issue!!

**Comment by narayananiyer86** [comment]
Im getting the same error. My store is woocommerce.

**Comment by DenysZP** [comment]
@narayananiyer86, @sharif-rcis did you initialize the API?
`val api = ShopifyApi(this, "BASE DOMAIN", "STOREFRONT ACCESS TOKEN", "API KEY", "API PASSWORD") //Initialize your api here.`

**Comment by narayananiyer86** [comment]
Hey.Im using woocommerce. How do i inititialize the api for woocommerce ?

**Comment by DenysZP** [comment]
@narayananiyer86 Please follow the [documentation](https://github.com/rubygarage/shopapp-android/blob/master/README.md).

**Comment by narayananiyer86** [comment]
Hello. Im on that page already. What should be put in place of Shopify. My store is WooCommerce.When i put WooCommerce it appears in RED

**Comment by DenysZP** [comment]
At the moment, the application does not support the implementation for the WooCommerce. You can implement the API for this platform yourself.

**Comment by narayananiyer86** [comment]
that will take time for us sir. any code/resources readily available for us to start ?

**Comment by DenysZP** [comment]
You can read the WooCommerce documentation and then create your own implementation of the [API](https://github.com/rubygarage/shopapp-android/blob/master/gateway/src/main/java/com/shopapp/gateway/Api.kt).

**Comment by narayananiyer86** [comment]
any alternative projects can you refer us to sir ? we are time crunched here .

**Comment by narayananiyer86** [comment]
alternative projects that are having the free to use commercial licesnce like yours.

**Comment by DenysZP** [comment]
Sorry, I have no information about this.
